services:
  main_local_mysql:
    image: mysql:8.0
    container_name: main_local_mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./main-mysql/data:/var/lib/mysql
      - ./main-mysql/conf.d:/etc/mysql/conf.d # mysql에 설정을 위한 폴더
    restart: unless-stopped

  tool_local_mysql:
    image: mysql:8.0
    container_name: tool_local_mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./tool-mysql/data:/var/lib/mysql
      - ./tool-mysql/conf.d:/etc/mysql/conf.d # mysql에 설정을 위한 폴더
    restart: unless-stopped

  main_local_redis:
    image: redis:7.0-alpine
    container_name: main_local_redis
    ports:
      - "6381:6379"
    command: ["redis-server", "--requirepass", "${MAIN_REDIS_PASSWORD}"]
    volumes:
      - ./main-redis/data:/data
      - ./main-redis/reds.conf:/usr/local/etc/redis/redis.conf:ro
    restart: unless-stopped

  tool_local_redis:
    image: redis:7.0-alpine
    container_name: tool_local_redis
    ports:
      - "6382:6379"
    command: ["redis-server", "--requirepass", "${TOOL_REDIS_PASSWORD}"]
    volumes:
      - ./tool-redis/data:/data
      - ./tool-redis/reds.conf:/usr/local/etc/redis/redis.conf:ro
    restart: unless-stopped